// GENERATED by scripts/generate-spot-pages.js — do not edit by hand.
// Maps production spot ids to their static page slugs.
window.KAAYKO_SPOT_SLUGS = {
  "ambazari": "ambazari-lake-nagpur",
  "antero": "antero-reservoir-colorado",
  "colorado": "colorado-river-moab-utah",
  "cottonwood": "cottonwood-lake-colorado",
  "crescent": "lake-crescent-washington",
  "diablo": "diablo-lake-washington",
  "jackson": "jackson-lake-wyoming",
  "jenny": "jenny-lake-wyoming",
  "kens": "kens-lake-utah",
  "lewisville": "lewisville-lake-texas",
  "mcdonald": "lake-mcdonald-montana",
  "merrimack": "merrimack-river-new-hampshire",
  "powell": "lake-powell-utah",
  "taylorpark": "taylor-park-reservoir-colorado",
  "trinity": "trinity-river-irving-texas",
  "union": "lake-union-seattle",
  "whiterock": "white-rock-lake-dallas"
};
